project:
  type: website

website:
  title: ""
  description: "Community College Planning and Research Organization"
  favicon: "images/ccpro-transparent-background.png"
  navbar:
    background: primary
    logo: "images/ccpro-white-nc-transparent-background.png"
    logo-href: "/"
    left:
      - href: index.qmd
        text: Home
      - href: pages/officers.qmd
        text: Officers
      - href: pages/membership-directory.qmd
        text: Membership Directory
      - href: pages/conferences.qmd
        text: Conferences/Meetings
      - href: pages/documents.qmd
        text: Documents
      - href: pages/resources.qmd
        text: Resources
      - href: pages/job-postings.qmd
        text: Job Postings

  page-footer:
    center: "CCPRO â€“ Community College Planning and Research Organization"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
