project:
  type: website

website:
  title: ""
  description: "Community College Planning and Research Organization"
  favicon: "images/CCPRO - transparent background.png"
  navbar:
    background: primary
    logo: "images/CCPRO - White NC - Transparent Background.png"
    left:
      - href: index.qmd
        text: Home
      - href: officers.qmd
        text: Officers
      - href: membership-directory.qmd
        text: Membership Directory
      - href: conferences.qmd
        text: Conferences/Meetings
      - href: documents.qmd
        text: Documents
      - href: resources.qmd
        text: Resources
      - href: job-postings.qmd
        text: Job Postings

  page-footer:
    center: "CCPRO â€“ Community College Planning and Research Organization"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
